<footer class="footer">
      
  <div class="footer__column footer__column--medium">
    <img src="assets/img/logo-footer.png" alt="Kiko Autos" class="footer__logo">
    <small class="footer__about">
      A KikoAutos tem como foco oferecer a seus clientes serviços agregados, não apenas um excelente automóvel 0KM ou seminovo.
      Por isso, serve como vitrine para o mercado e se destaca pelo seu atendimento de qualidade, consultores altamente treinados
      e infraestrutura moderna e diferenciada.
    </small>
    
    <div class="social social--big">
      <ul class="social__list">
        <li class="social__item">
          <a href="#!">
            <img src="assets/img/icons/facebook.svg" alt="Facebook">
          </a>
        </li>
        <li class="social__item">
          <a href="#!">
            <img src="assets/img/icons/instagram.svg" alt="Instagram">
          </a>
        </li>
        <li class="social__item">
          <a href="#!">
            <img src="assets/img/icons/whatsapp.svg" alt="WhatsApp">
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="footer__column footer__column--small">
    <h5 class="footer__title">LINKS</h5>
    
    <ul class="footer__list">
      <li>
        <a href="sobre.html">Sobre</a>
      </li>
      <li>
        <a href="estoque.php">Novos</a>
      </li>
      <li>
        <a href="estoque.php">Seminovos</a>
      </li>
      <li>
        <a href="financiamento.html">Financiamento</a>
      </li>
      <li>
        <a href="consorcio.html">Consórcio</a>
      </li>
      <li>
        <a href="contato">Contato</a>
      </li>
    </ul>
  </div>
          

  <div class="footer__column">
    <h5 class="footer__title">CONTATO</h5>
    
    <address class="footer__address">
      <div class="footer__contact icon-text">
        <img src="assets/img/icons/pin.svg" alt="Local">
        <p>Rua Dr. Emilio Winther, 68.
          <br>Centro Taubaté / SP</p>
      </div>
      <div class="footer__contact icon-text">
        <img src="assets/img/icons/clock.svg" alt="Horário">
        <p>Segunda à sexta das 9h às 18h30 Sábado das 9h às 13h</p>
      </div>
    
      <div class="footer__contact footer__contact--big icon-text">
        <img src="assets/img/icons/phone.svg" alt="Horário">
        <p>12 3632 3200</p>
      </div>
    </address>
  </div>

  <div class="footer__column">
    <h5 class="footer__title">CONTATO</h5>
    
    <address class="footer__address">
      <div class="footer__contact icon-text">
        <img src="assets/img/icons/pin.svg" alt="Local">
        <p>Rua Dr. Emilio Winther, 68.
          <br>Centro Taubaté / SP</p>
      </div>
      <div class="footer__contact icon-text">
        <img src="assets/img/icons/clock.svg" alt="Horário">
        <p>Segunda à sexta das 9h às 18h30<br>Sábado das 9h às 13h</p>
      </div>
    
      <div class="footer__contact footer__contact--big icon-text">
        <img src="assets/img/icons/phone.svg" alt="Horário">
        <p>12 3632 3200</p>
      </div>
    </address>
  </div>

</footer>
<div class="footer__bottom">
  <small>
    Todos os direitos reservados
    <span>Kiko Autos Automóveis 2017.</span>
  </small>

  <div class="powered-by-inffus">
    <a title="Desenvolvido pela Inffus" href="http://inffus.com" target="_blank">
      <img src="http://inffus.com/inffus-web-intelligence.svg" width="20">
    </a>
  </div>
</div>