<header class="header">
      <div class="header-aux">
        <div class="hamburger">
          <div class="hamburger-box">
          </div>
        </div>
        
        <a href="index.html" class="header-aux__logo">
          <img src="assets/img/logo.png" alt="Kiko Autos">
        </a>
      </div>

      <div class="header-top">
        <div class="header-top__content">
          <small class="header__slogan">KIKOAUTOS - Multimarcas . Multipossibilidades.</small>
          
          <div class="social">
            <ul class="social__list">
              <li class="social__item">
                <a href="#!">
                  <img src="assets/img/icons/facebook.svg" alt="Facebook">
                </a>
              </li>
              <li class="social__item">
                <a href="#!">
                  <img src="assets/img/icons/instagram.svg" alt="Instagram">
                </a>
              </li>
              <li class="social__item">
                <a href="#!">
                  <img src="assets/img/icons/whatsapp.svg" alt="WhatsApp">
                </a>
              </li>
              <li>
                <div class="icon-text">
                  <img src="assets/img/icons/phone.svg" alt="Telefone">
                  <p>+55 12 3632 3200</p>
                </div>
              </li>
            </ul>
          </div>

        </div>
      </div>

      <div class="header-bottom">
        <div class="header-bottom__content">
          <a href="index.html" class="header__logo">
            <img src="assets/img/logo.png" alt="Kiko Autos">
          </a>

          <nav class="menu">
            <ul class="menu__list">
              <li class="menu__item"><a href="/sobre" class="menu__link">Sobre</a></li>
              <li class="menu__item"><a href="/estoque" class="menu__link">Novos</a></li>
              <li class="menu__item"><a href="/estoque" class="menu__link">Seminovos</a></li>
              <li class="menu__item"><a href="/financiamento" class="menu__link">Financiamento</a></li>
              <li class="menu__item"><a href="/consorcio" class="menu__link">Consórcio</a></li>
              <li class="menu__item"><a href="/contato" class="menu__link">Contato</a></li>
              <li class="menu__item">
                <div class="search">
                  <button class="search__button js-toggle-search">
                    <img src="assets/img/icons/search.svg" alt="Buscar">
                  </button>
                  
                  <div class="search__content">
                    <input type="text" name="input_busca" value="" placeholder="Buscar veículo..." class="js-search">
                    
                    <div class="search__result"></div>
                  </div>
                </div>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </header>