<section class="section newsletter hidden-print">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>ASSINE NOSSO NEWSLETTER</h2>
      <p>Fique por dentro das novidades do mundo automotivo, acompanhe lançamentos do nosso estoque de veículos novos e seminovos, além de  receber em primeira mão informações sobre vantagens e promoções.</p>
    </div>        
  </div>
</header>

<div class="k-container hidden-print">
  <div class="section__content">
    <form class="form form--inline" id="formNewsletter">
      <div class="form__control">
        <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
        <span class="form__error">*</span>
      </div>

      <div class="form__control">
        <input type="email" class="input" placeholder="E-MAIL" name="email">
        <span class="form__error">*</span>
      </div>

      <div class="form__control">
        <button type="submit" class="button button--arrow button--large">cadastrar</button>
      </div>
    </form>

    <small class="newsletter__small">
       A Kikoautos se compromete em não utilizar seus dados para outros fins, compartilhar suas informações com terceiros ou divulgar seus dados publicamente.
    </small>
  </div>
</div>
</section>