<section class="section section--white hidden-print">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>KIKOAUTOS NO INSTAGRAM</h2>
      <p>Acompanhe em tempo real nossos stories e postagens no Instagram e saiba todos os detalhes do nosso estoque.</p>
    </div>
  </div>
</header>

<div class="section__content hidden-print">
  <div id="instafeed" class="instafeed"></div>
</div>
<a href="https://www.instagram.com/kikoautos" class="instafeed__link" target="_blank">
   https://www.instagram.com/kikoautos
</a>
</section>