<section class="section section--white hidden-print">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>SERVIÇOS</h2>
      <p>A Kikoautos tem como foco oferecer a seus clientes serviços agregados, não apenas um excelente automóvel. Confira nossos principais serviços e formas de negociação para garantir sua melhor experiência.</p>
    </div>
  </div>        
</header>

<div class="section__content section__content--top">
  <div class="media media--horizontal media--full">
  
    <a href="/financiamento" class="media__item">
      <div class="media__img" style="background-image: url(/assets/img/p1.jpg);"></div>
      <div class="media__desc media__desc--gray">
        <h4 class="media__title">FINANCIAMENTO</h4>
      </div>
    </a>
  
    <a href="/consorcio" class="media__item">
      <div class="media__img" style="background-image: url(/assets/img/p2.jpg);"></div>
      <div class="media__desc media__desc--red">
        <h4 class="media__title">CONSÓRCIO</h4>
      </div>
    </a>
  
    <a href="/consignado" class="media__item">
      <div class="media__img" style="background-image: url(/assets/img/p3.jpg);"></div>
      <div class="media__desc media__desc--blue">
        <h4 class="media__title">VENDA SEU CARRO</h4>
      </div>
    </a>
  
  </div>
</div>
</section>