<div class="media media--horizontal media--full">  
        <div class="media__item">
          <div class="media__img" style="background-image: url(assets/img/p3.jpg);"></div>
          <div class="media__desc media__desc--blue">
            <h4 class="media__title">VENDA SEU CARRO</h4>
          </div>
        </div>
      </div>

      <section class="section">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>SEU VEÍCULO CONSIGNADO</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="media media--col4 media--center">
      
            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/fotos.png" alt="Variedade de marcas">
              </div>
              <div class="media__desc">
                <h4 class="media__title">FOTOS
                  <br>PROFISSIONAIS
                </h4>
                <p class="media__text">
                   Imagens que valorizam ainda mais a venda do seu carro
                </p>
              </div>
            </div>
      
            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/seguidores.png" alt="Negociação facilitada">
              </div>
              <div class="media__desc">
                <h4 class="media__title">MAIS DE 20 MIl
                  <br>SEGUIDORES
                </h4>
                <p class="media__text">Seu carro em nossas mídias sociais</p>
              </div>
            </div>
      
            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/tempo-recorde.png" alt="Certificação de blindados">
              </div>
              <div class="media__desc">
                <h4 class="media__title">TEMPO
                  <br>RECORDE
                </h4>
                <p class="media__text">
                  Veículos vendidos em menos de 24hrs
                </p>
              </div>
            </div>
      
            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/dinheiro.png" alt="Estrutura Moderna">
              </div>
              <div class="media__desc">
                <h4 class="media__title">DESTACAMOS O
                  <br>SEU PRODUTO
                </h4>
                <p class="media__text">
                  Investimos em todas plataformas de venda Online
                </p>
              </div>
            </div>
      
          </div>
        </div>
      
        <p class="section__message">
           Não perca a venda, solicite contato pelo formulário:
        </p>
      </section>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>PREENCHA O FORMULÁRIO</h2>
              <p>Todos os campos são obrigatórios. Caso você tiver alguma dificuldade
                <a href="contato.html" class="k-link">entre em contato</a>.</p>
            </div>
          </div>          
        </header>
        <div class="section__content">
          <div class="container">
            <form class="form" action="" id="formConsignado">
              <div class="row">
                <div class="col-md-6">

                  <div class="form__control">
                    <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                  </div>

                  <div class="form__control">
                    <input type="email" class="input" placeholder="EMAIL" name="email">
                  </div>

                  <div class="form__control">
                    <input type="tel" class="input js-phone" placeholder="TELEFONE" name="telefone">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input js-cpfcnpj" placeholder="CPF/CNPJ" name="cpfcnpj">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="ENDEREÇO COMPLETO" name="endereco">
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form__control">
                    <input type="text" class="input" placeholder="MARCA DO VEÍCULO" name="marca">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="MODELO DO VEÍCULO" name="modelo">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input js-ano" placeholder="ANO DE FABRICAÇÃO E MODELO" name="ano">
                  </div>

                  <div class="form__control">
                    <textarea name="detalhes" class="textarea" placeholder="INFORME MAIS DETALHES DO VEÍCULO"></textarea>
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form__control">
                    <input type="checkbox" id="novidades_email" />
                    <label for="novidades_email">Receber novidades por e-mail</label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form__control text-right">
                    <button type="submit" class="button button--arrow button--ghost button--medium">ENVIAR</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </section>

      <section>
        <div class="media media--horizontal media--full">
          <a href="consorcio.html" class="media__item">
            <div class="media__img" style="background-image: url(assets/img/p2.jpg);"></div>
            <div class="media__desc media__desc--red">
              <h4 class="media__title">CONSÓRCIO</h4>
            </div>
          </a>
      
          <a href="financiamento.html" class="media__item">
            <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
            <div class="media__desc media__desc--gray">
              <h4 class="media__title">FINANCIAMENTO</h4>
            </div>
          </a>
      
        </div>
      </section>

      <section class="section newsletter">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>ASSINE NOSSO NEWSLETTER</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
      
        <div class="k-container">
          <div class="section__content">
            <form class="form form--inline" id="formNewsletter">
              <div class="form__control">
                <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                <span class="form__error">*</span>
              </div>
      
              <div class="form__control">
                <input type="email" class="input" placeholder="E-MAIL" name="email">
                <span class="form__error">*</span>
              </div>
      
              <div class="form__control">
                <button type="submit" class="button button--arrow button--large">cadastrar</button>
              </div>
            </form>
      
            <small class="newsletter__small">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
              dolor sit amet, consectetur adipiscing elit.
            </small>
          </div>
        </div>
      </section>