<div class="media media--horizontal media--full">  
        <div class="media__item">
          <div class="media__img" style="background-image: url(assets/img/p2.jpg);"></div>
          <div class="media__desc media__desc--red">
            <h4 class="media__title">CONSÓRCIO</h4>
          </div>
        </div>
      </div>

      <section class="section consorcio section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>KikoAUTOS E Vinac</h2>
              <p>Duas marcas consolidadas, unindo seus serviços para multiplicar seus sonhos. Uma parceria que traz para você a confiança
                dos consórcios Vinac, a exclusividade KikoAutos e a credibilidade das duas grandes empresas.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="consorcio__marcas">
            <img src="assets/img/logo.png" alt="Kiko Autos">
            <img src="assets/img/logo-vinac.png" alt="VINAC">
          </div>
        </div>
      </section>

      <section class="section ">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>VANTAGENS</h2>
              <p>Vinac Consórcios é uma das maiores administradoras de consórcios do país. Muito respeitada pela pontualidade na entrega de
                suas cartas de crédito, pela transparência e respeito aos seus clientes.</p>
            </div>
          </div>
        </header>
        <div class="section__content vantagens">
          <div class="container">
            <div class="vantagens__content">
              <div class="vantagens__group">
                <img src="assets/img/porco.png" alt="">
              </div>
              <div class="vantagens__group">
                <div class="vantagens__item">
                  <p>Taxa de administração de apenas 12% (a menor do mercado)</p>
                </div>

                <div class="vantagens__item">
                  <p>Aceitamos seu usado como lance</p>
                </div>

                <div class="vantagens__item">
                  <p>2 clientes contemplados todos os meses</p>
                </div>

                <div class="vantagens__item">
                  <p>Apenas 120 pessoas por grupo</p>
                </div>

                <div class="vantagens__item">
                  <p>Liberdade na escolha do bem, zero km ou seminovo</p>
                </div>

                <div class="vantagens__item">
                  <p>Livre de burocracia e total agilidade no pagamento do contemplado</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>GRUPOS ABERTOS</h2>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <div class="row">
              <div class="col-md-6">
                <table class="table">
                  <caption>GRUPO 703 | 60 meses | 1ª assembleia: 26/10/2017 as 20 horas</caption>
                  <thead>
                    <tr>
                      <th>VEÍCULO</th>
                      <th>CRÉDITO</th>
                      <th>PRESTAÇÃO</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                  </tbody>
                </table>

                <div class="table__action">
                  <span>Vencimentos todo dia 10 do mês</span>
                  <button class="button button--red button--ghost">
                    ENTRAR NO GRUPO
                  </button>
                </div>
              </div>
              <div class="col-md-6">
                <table class="table">
                  <caption>GRUPO 703 | 60 meses | 1ª assembleia: 26/10/2017 as 20 horas</caption>
                  <thead>
                    <tr>
                      <th>VEÍCULO</th>
                      <th>CRÉDITO</th>
                      <th>PRESTAÇÃO</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                    <tr>
                      <td>lorem ipsum</td>
                      <td>R$ 34.000,00</td>
                      <td>R$ 599</td>
                    </tr>
                  </tbody>
                </table>

                <div class="table__action">
                  <span>Vencimentos todo dia 10 do mês</span>
                  <button class="button button--red button--ghost">
                    ENTRAR NO GRUPO
                  </button>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12">
                <div class="button-group">
                  <button class="button button--ghost button--blue button--medium">
                    IMPRIMIR ESTA PÁGINA?
                  </button>
                  <button class="button button--ghost button--green button--medium">
                    DÚVIDAS? FALE CONOSCO
                  </button>
                </div>
              </div>
            </div>

            <div class="text--small">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
              ac dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, con- sectetur adipiscing elit. Aenean ac
              tortor at tellus feugiat congue quis ut nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at
              tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet,
              con- sectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc.
            </div>
          </div>
        </div>
      </section>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>OUTROS SERVIÇOS</h2>
            </div>
          </div>
          
        </header>
        <div class="media media--horizontal media--full">
          <a href="financiamento.html" class="media__item">
            <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
            <div class="media__desc media__desc--gray">
              <h4 class="media__title">FINANCIAMENTO</h4>
            </div>
          </a>
        </div>
      </section>

      <section class="section newsletter">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>ASSINE NOSSO NEWSLETTER</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>          
        </header>
      
        <div class="k-container">
          <div class="section__content">
            <form class="form form--inline" id="formNewsletter">
              <div class="form__control">
                <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                <span class="form__error">*</span>
              </div>
      
              <div class="form__control">
                <input type="email" class="input" placeholder="E-MAIL" name="email">
                <span class="form__error">*</span>
              </div>
      
              <div class="form__control">
                <button type="submit" class="button button--arrow button--large">cadastrar</button>
              </div>
            </form>
      
            <small class="newsletter__small">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
              dolor sit amet, consectetur adipiscing elit.
            </small>
          </div>
        </div>
      </section>