<section class="section">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>FALE CONOSCO</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <form class="form" action="" id="formContato">
              <div class="row">
                <div class="col-md-4">

                  <div class="form__control">
                    <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                  </div>

                  <div class="form__control">
                    <input type="email" class="input" placeholder="EMAIL" name="email">
                  </div>

                  <div class="form__control">
                    <input type="tel" class="input js-phone" placeholder="TELEFONE" name="telefone">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="ENDEREÇO" name="endereco">
                  </div>
                </div>

                <div class="col-md-8">

                  <div class="form__control form__control--select">
                    <select class="input" name="assunto" id="assunto">
                      <option value="0" disabled selected>ASSUNTO</option>
                      <option value="1">ASSUNTO 1</option>
                      <option value="2">ASSUNTO 2</option>
                    </select>
                  </div>

                  <div class="form__control">
                    <textarea name="mensagem" class="textarea textarea--big" placeholder="Olá, estou interessado no veículo Hyundai New Tucson"></textarea>
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form__control">
                    <input type="checkbox" id="novidades_email" />
                    <label for="novidades_email">Receber novidades por e-mail</label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form__control text-right">
                    <button type="submit" class="button button--arrow button--ghost button--medium">ENVIAR</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </section>

      <section class="section section--white section--padding-bottom">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>SERVIÇOS</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
        </header>
      </section>

      <section>
        <div class="media media--horizontal media--full">
          <a href="financiamento.html" class="media__item">
            <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
            <div class="media__desc media__desc--gray">
              <h4 class="media__title">FINANCIAMENTO</h4>
            </div>
          </a>

          <a href="consorcio.html" class="media__item">
            <div class="media__img" style="background-image: url(assets/img/p2.jpg);"></div>
            <div class="media__desc media__desc--red">
              <h4 class="media__title">CONSÓRCIO</h4>
            </div>
          </a>

          

        </div>
      </section>

      <section class="section newsletter">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>ASSINE NOSSO NEWSLETTER</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc.
                Semper ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>

        <div class="k-container">
          <div class="section__content">
            <form class="form form--inline" id="formNewsletter">
              <div class="form__control">
                <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                <span class="form__error">*</span>
              </div>

              <div class="form__control">
                <input type="email" class="input" placeholder="E-MAIL" name="email">
                <span class="form__error">*</span>
              </div>

              <div class="form__control">
                <button type="submit" class="button button--arrow button--large">cadastrar</button>
              </div>
            </form>

            <small class="newsletter__small">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
              dolor sit amet, consectetur adipiscing elit.
            </small>
          </div>
        </div>
      </section>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>KIKOAUTOS NO INSTAGRAM</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
      
        <div class="section__content">
          <div id="instafeed" class="instafeed"></div>
        </div>
      
        <a hreft="https://www.instagram.com/kikoautos" class="instafeed__link" target="_blank">
          https://www.instagram.com/kikoautos
        </a>
      </section>