<section class="section">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>FALE CONOSCO</h2>
              <p>Entre em contato conosco, tire suas dúvidas, solicite atendimento ou se preferir entre em contato via WhatsApp pelo número (12) 99630-7771.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <form class="form" id="formContato" method="post">
              <div class="row">
                <div class="col-md-4">

                  <div class="form__control">
                    <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                  </div>

                  <div class="form__control">
                    <input type="email" class="input" placeholder="EMAIL" name="email">
                  </div>

                  <div class="form__control">
                    <input type="tel" class="input js-phone" placeholder="TELEFONE" name="telefone">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="ENDEREÇO" name="endereco">
                  </div>
                </div>

                <div class="col-md-8">

                  <div class="form__control">
	                <input type="text" class="input" placeholder="ASSUNTO" value="<?=urldecode($assuntoContato)?>"  name="assunto" id="assunto">  
                  </div>

                  <div class="form__control">
                    <textarea name="mensagem" class="textarea textarea--big" placeholder="Olá, estou interessado no veículo Hyundai New Tucson"></textarea>
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form__control">
                    <input type="checkbox" name="newsletter" value="1" id="novidades_email" />
                    <label for="novidades_email">Receber novidades por e-mail</label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form__control text-right">
                    <button type="submit" class="button button--arrow button--ghost button--medium">ENVIAR</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </section>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	//include_once('include/section-servicos.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	//include_once('include/section-newsletter.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	//include_once('include/section-instagram.phtml');	

?>