<div class="section section--no-padding filtro js-filter">
<button class="filtro__item filtro__item--green" data-filter=".grid__item--seminovo">
  <h3>SEMINOVOS</h3>
  <img src="assets/img/seminovos.png" alt="Seminovos">
</button>
<button class="filtro__item filtro__item--red" data-filter=".grid__item--novo">
  <h3>NOVOS</h3>
  <img src="assets/img/novos.png" alt="Novo">
</button>
<button class="filtro__item filtro__item--blue" data-filter=".grid__item--blindado">
  <h3>BLINDADOS</h3>
  <img src="assets/img/blindados.png" alt="Blindado">
</button>
</div>

<section class="section section--white">
<div class="section__header">
  <div class="container">
    <h2>ESTOQUE</h2>
    <p>Confira nosso estoque multimarcas de veículos novos, seminovos e blindados. Realize busca por palavras-chave, utilize os filtros por marcas, modelos e organize os resultados por preço ou ano de fabricação.</p>
  </div>
</div>
<div class="section__content section--padding-bottom">
  <div class="container">
    <div class="form form--inline">
      <div class="form__control">
        <input class="input quicksearch" type="search" placeholder="FILTRAR POR TERMOS">
      </div>
      <div class="form__control form__control--select">
        <select class="select" name="marca" id="marca">
          <option value="0" disabled selected>FILTRAR POR MARCA</option>
          <option value="*">TODOS</option>
          
          <?php 
	                      
            //Seleciona veciculos destacados
            if(count($veiculoFiltrosMarca)>0){
                
			for($m=0;$m<count($veiculoFiltrosMarca);$m++){ 
		  ?>
		  
		  	<option value=".<?=$veiculoFiltrosMarca[$m]->idMarca?>"><?=$veiculoFiltrosMarca[$m]->idMarca?></option>
		  	
		  
		  <?php } } ?>
          
        </select>
      </div>
      <div class="form__control form__control--select">
        <select class="select" name="modelo" id="modelo">
          <option value="0" disabled selected>FILTRAR POR MODELO</option>
          <option value="*">TODOS</option>
          
          <?php 
	                      
            //Seleciona veciculos destacados
            if(count($veiculoFiltrosModelo)>0){
                
			for($x=0;$x<count($veiculoFiltrosModelo);$x++){ 
		  ?>
		  
		  	<option value=".<?=$veiculoFiltrosModelo[$x]->alias?>"><?=$veiculoFiltrosModelo[$x]->modelo?></option>
		  	
		  
		  <?php } } ?>

        </select>
      </div>
      <div class="form__control form__control--select">
        <select class="select" name="ordem" id="ordem">
          <option value="0" disabled selected>ORDENAR POR</option>
          <option value="*">TODOS</option>
          <option value="valor">VALOR</option>
          <option value="ano">ANO</option>
        </select>
      </div>
    </div>
  </div>
</div>
</section>

<section class="grid section section--no-padding section--white">
<div class="section__grid">

  <div class="grid js-grid" id="Container">

  </div>
</div>

<footer class="grid__footer">
  <div class="container">
  </div>
</footer>


</section>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-servicos.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-newsletter.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-instagram.phtml');	

?>