<div class="media media--horizontal media--full">
        <div class="media__item">
          <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
          <div class="media__desc media__desc--gray">
            <h4 class="media__title">FINANCIAMENTO</h4>
          </div>
        </div>
      </div>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>PREENCHA O FORMULÁRIO</h2>
              <p>Todos os campos são obrigatórios. Caso você tiver alguma dificuldade
                <a href="contato.html" class="k-link">entre em contato</a>.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <form class="form" action="" id="formFinanciamento">
              <div class="row">
                <div class="col-md-6">

                  <div class="form__control">
                    <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                  </div>

                  <div class="form__control">
                    <input type="email" class="input" placeholder="EMAIL" name="email">
                  </div>

                  <div class="form__control">
                    <input type="tel" class="input js-phone" placeholder="TELEFONE" name="telefone">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="VALOR QUE DESEJA FINANCIAR" name="valor_financiar">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="QUANTIDADE DE PARCELAS" name="qtd_parcelas">
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form__control">
                    <input type="text" class="input js-cpfcnpj" placeholder="CPF/CNPJ" name="cpfcnpj">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input js-date" placeholder="DATA DE NASCIMENTO/FUNDAÇÃO" name="data_nascimento">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="ENDEREÇO" name="endereco">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="VALOR DA ENTRADA" name="valor_entrada">
                  </div>

                  <div class="form__control form__control--select">
                    <select class="input" name="veiculo_interesse" id="veiculo_interesse">
                      <option value="0" disabled selected>VEÍCULO DE INTERESSE</option>
                      <option value="1">Veículo 1</option>
                      <option value="2">Veículo 2</option>
                    </select>
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form__control">
                    <input type="checkbox" id="novidades_email" />
                    <label for="novidades_email">Receber novidades por e-mail</label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form__control text-right">
                    <button type="submit" class="button button--arrow button--ghost button--medium">ENVIAR</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </section>

      <section>
        <div class="media media--horizontal media--full">
          <a href="consorcio.html" class="media__item">
            <div class="media__img" style="background-image: url(assets/img/p2.jpg);"></div>
            <div class="media__desc media__desc--red">
              <h4 class="media__title">CONSÓRCIO</h4>
            </div>
          </a>
        </div>
      </section>

      <section class="section newsletter">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>ASSINE NOSSO NEWSLETTER</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc.
                Semper ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>

        <div class="k-container">
          <div class="section__content">
            <form class="form form--inline" id="formNewsletter">
              <div class="form__control">
                <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                <span class="form__error">*</span>
              </div>

              <div class="form__control">
                <input type="email" class="input" placeholder="E-MAIL" name="email">
                <span class="form__error">*</span>
              </div>

              <div class="form__control">
                <button type="submit" class="button button--arrow button--large">cadastrar</button>
              </div>
            </form>

            <small class="newsletter__small">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
              dolor sit amet, consectetur adipiscing elit.
            </small>
          </div>
        </div>
      </section>