<div class="media media--horizontal media--full">
        <div class="media__item">
          <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
          <div class="media__desc media__desc--gray">
            <h4 class="media__title">FINANCIAMENTO</h4>
          </div>
        </div>
      </div>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>PREENCHA O FORMULÁRIO</h2>
              <p>Todos os campos são obrigatórios. Caso você tiver alguma dificuldade
                <a href="/contato" class="k-link">entre em contato</a>.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <form class="form" action="" id="formFinanciamento">
              <div class="row">
                <div class="col-md-6">

                  <div class="form__control">
                    <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                  </div>

                  <div class="form__control">
                    <input type="email" class="input" placeholder="EMAIL" name="email">
                  </div>

                  <div class="form__control">
                    <input type="tel" class="input js-phone" placeholder="TELEFONE" name="telefone">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="VALOR QUE DESEJA FINANCIAR" name="valor_financiar">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="QUANTIDADE DE PARCELAS" name="qtd_parcelas">
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="form__control">
                    <input type="text" class="input js-cpfcnpj" placeholder="CPF/CNPJ" name="cpfcnpj">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input js-date" placeholder="DATA DE NASCIMENTO/FUNDAÇÃO" name="data_nascimento">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="ENDEREÇO" name="endereco">
                  </div>

                  <div class="form__control">
                    <input type="text" class="input" placeholder="VALOR DA ENTRADA" name="valor_entrada">
                  </div>

                  <div class="form__control form__control--select">
                    <select class="input" name="idVeiculo" id="veiculo_interesse">
                      <option value="0" disabled selected>VEÍCULO DE INTERESSE</option>
                      
                      <?php 
	                      
	                    //Seleciona veciculos destacados
	                    if(count($veiculoAtivos)>0){
		                    
						for($x=0;$x<count($veiculoAtivos);$x++){ 
					  ?>
                      	<option value="<?=$veiculoAtivos[$x]->idVeiculo?>"><?=$veiculoAtivos[$x]->idMarca?> <?=$veiculoAtivos[$x]->modelo?> - <?=$veiculoAtivos[$x]->anoFabricacao?>/<?=$veiculoAtivos[$x]->anoModelo?> - R$ <?=$veiculoAtivos[$x]->preco?></option>
					  
					  <?php } } ?>
					  
                    </select>
                  </div>
                </div>

              </div>

              <div class="row">
                <div class="col-md-6">
                  <div class="form__control">
                    <input type="checkbox" name="newsletter" value="1" id="novidades_email" />
                    <label for="novidades_email">Receber novidades por e-mail</label>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form__control text-right">
                    <button type="submit" class="button button--arrow button--ghost button--medium">ENVIAR</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </section>

      <section>
        <div class="media media--horizontal media--full">
          <a href="/consorcio" class="media__item">
            <div class="media__img" style="background-image: url(/assets/img/p2.jpg);"></div>
            <div class="media__desc media__desc--red">
              <h4 class="media__title">CONSÓRCIO</h4>
            </div>
          </a>
          
          <a href="/consignado" class="media__item">
		      <div class="media__img" style="background-image: url(/assets/img/p3.jpg);"></div>
		      <div class="media__desc media__desc--blue">
		        <h4 class="media__title">VENDA SEU CARRO</h4>
		      </div>
		    </a>
          
        </div>
      </section>

     	<?php

			/*
			* Incluse Newsletter
			*	
			*/
			
			include_once('include/section-newsletter.phtml');	
		
		?>
		
		<?php
		
			/*
			* Incluse Newsletter
			*	
			*/
			
			include_once('include/section-instagram.phtml');	
		
		?>