<section class="banner js-banner-slider">
	<?php for($i=0;$i<count($bannerPrincipal);$i++){  ?>  
		<a href="<?=$bannerPrincipal->link?>">
		<div class="banner__item" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$bannerPrincipal[$i]->idAlbum?>/<?=$bannerPrincipal[$i]->file?>);"></div>
		</a>
	<?php } ?>
</section>

<section class="section">

	<header class="section__header">
	  <div class="container">
	    <div class="col-md-8 col-md-offset-2">
	      <h2>Novos</h2>
	      <p>Confira nosso estoque multimarcas de veículos zero quilômetro e surpreenda-se com as vantagens que só a Kikoautos pode oferecer além das concessionárias.</p>
	    </div>
	  </div>
	</header>

	<div class="section__content">
	
	<?php
		    
	if(count($veiculoDestaqueNovos)>3){  ?>
	
	  <div class="grid-slider js-grid-slider">
	
	    <?php
	
		//Seleciona veciculos destacados
		for($x=0;$x<count($veiculoDestaqueNovos);$x++){ 
			
			$rowDestaqueNovo = $veiculoDestaqueNovos[$x]; 	
			
			$marcaNovo 			= DAOFactory::getMarcaDAO()->load($rowDestaqueNovo->idMarca);
			$transmissaoNovo 	= DAOFactory::getTransmissaoDAO()->load($rowDestaqueNovo->idTransmissao);
			$categoriaNovo	 	= DAOFactory::getVeiculoCategoriaDAO()->load($rowDestaqueNovo->idVeiculoCategoria);
			$capaNovo 			= DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowDestaqueNovo->idAlbum.'" ORDER BY ordem ASC LIMIT 1 '); 
		
		?>
	
	    <a href="/veiculo/<?=$rowDestaqueNovo->alias?>/<?=$rowDestaqueNovo->idVeiculo?>" class="grid__item">
	      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowDestaqueNovo->idAlbum?>/<?=$capaNovo[0]->file?>);"></div>
	      <div class="grid__desc">
	        <h3 class="grid__title"><?=$marcaNovo->nome?> <?=$rowDestaqueNovo->modelo?> <?=$rowDestaqueNovo->anoFabricacao?>/<?=$rowDestaqueNovo->anoModelo?></h3>
	        <p class="grid__text"><?=$rowDestaqueNovo->conservacao?> / <?=$transmissaoNovo->tipo?> / <?=$categoriaNovo->nome?></p>
	        <div class="grid__price">
	          R$ <?=$rowDestaqueNovo->preco?>
	        </div>
	      </div>
	    </a>
	    
	    <?php } ?>
	  
	  </div>
	  
	<?php }else{ ?>
		
		<p class="text-center">Nenhum veículo em destaque! Veja <a href="/estoque">nosso estoque completo</a>.</p> 
	    
	<?php } ?>  
	  
	</div>

	<a href="/estoque" class="button button--huge button--arrow">VER TODOS</a> 

</section>


<section class="grid section section--white">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>SEMINOVOS</h2>
      <p>Confira nosso estoque multimarcas de veículos seminovos com garantia de procedência, qualidade e multipossibilidades na negociação.</p>
    </div>
  </div>
</header>
<div class="section__content">

  <div class="grid js-grid-semi">      
    
        
  </div>
</div>

<a href="/estoque" class="button button--huge button--arrow">VER TODOS</a>
</section>

<section class="section">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>NOSSOS DIFERENCIAIS</h2>
      <p>Profissionalismo e foco no atendimento, em um ambiente inovador e dinâmico. Confira esses e outros diferenciais que fazem da Kikoautos a sua melhor opção em novos e seminovos na região.</p>
    </div>
  </div>
</header>
<div class="section__content">
  <div class="media media--col4 media--center">

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre#veriedade"><img src="/assets/img/variedade.png" alt="Variedade de marcas"></a>
      </div>
       <div class="media__desc">
         <h4 class="media__title">Variedade de<br>marcas</h4>
       </div>
    </div>

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre#negociacao"><img src="/assets/img/negociacao.png" alt="Negociação facilitada"></a>
      </div>
      <div class="media__desc">
        <h4 class="media__title">Negociação<br>facilitada</h4>
      </div>
    </div>

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre#certificacao"><img src="/assets/img/certificacao.png" alt="Certificação de blindados"></a>
      </div>
      <div class="media__desc">
        <h4 class="media__title">Certificação de<br>blindados</h4>
      </div>
    </div>

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre#estrutura"><img src="/assets/img/estrutura.png" alt="Estrutura Moderna"></a>
      </div>
      <div class="media__desc">
        <h4 class="media__title">Estrutura<br>Moderna</h4>
      </div>
    </div>

  </div>
</div>

<a href="/sobre" class="button button--huge button--arrow">SAIBA MAIS</a>
</section>


<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-servicos.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-newsletter.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-instagram.phtml');	

?>

