
      <section class="banner js-banner-slider">
        <div class="banner__item" style="background-image: url(assets/img/banner2.jpg);"></div>
        <div class="banner__item" style="background-image: url(assets/img/banner2.jpg);"></div>
      </section>

      <section class="section">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>Novos</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
        <div class="section__content">

          <div class="grid-slider js-grid-slider">

            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c1.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>

            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c2.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>

            <a href="veiculo.php" class="grid__item grid__item--blindado">
              <div class="grid__img" style="background-image:url(assets/img/carros/c3.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>



            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c1.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
            
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c2.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
            
            <a href="veiculo.php" class="grid__item grid__item--blindado">
              <div class="grid__img" style="background-image:url(assets/img/carros/c3.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>



            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c1.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
            
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c2.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>

            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c2.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
          
          </div>
        </div>

        <a href="#!" class="button button--huge button--arrow">VER TODOS</a> 

      </section>


      <section class="grid section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>SEMINOVOS</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
      
          <div class="grid js-grid">      
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c1.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c2.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item grid__item--blindado">
              <div class="grid__img" style="background-image:url(assets/img/carros/c3.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c1.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c2.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item grid__item--blindado">
              <div class="grid__img" style="background-image:url(assets/img/carros/c3.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item">
              <div class="grid__img" style="background-image:url(assets/img/carros/c1.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
      
            <a href="veiculo.php" class="grid__item grid__item--blindado">
              <div class="grid__img" style="background-image:url(assets/img/carros/c3.jpg)"></div>
              <div class="grid__desc">
                <h3 class="grid__title">BMW E46 M3 DISKI SERIE 2011/2012</h3>
                <p class="grid__text">NOVO / AUTOMATICO / SEDAN</p>
                <div class="grid__price">
                  R$ 98.000,00
                </div>
              </div>
            </a>
          </div>
        </div>

        <a href="#!" class="button button--huge button--arrow">VER TODOS</a>
      </section>

      <section class="section">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>NOSSOS DIFERENCIAIS</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
              dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="media media--col4 media--center">

            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/variedade.png" alt="Variedade de marcas">
              </div>
               <div class="media__desc">
                 <h4 class="media__title">Variedade de<br>marcas</h4>
               </div>
            </div>

            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/negociacao.png" alt="Negociação facilitada">
              </div>
              <div class="media__desc">
                <h4 class="media__title">Negociação<br>facilitada</h4>
              </div>
            </div>

            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/certificacao.png" alt="Certificação de blindados">
              </div>
              <div class="media__desc">
                <h4 class="media__title">Certificação de<br>blindados</h4>
              </div>
            </div>

            <div class="media__item">
              <div class="media__img">
                <img src="assets/img/estrutura.png" alt="Estrutura Moderna">
              </div>
              <div class="media__desc">
                <h4 class="media__title">Estrutura<br>Moderna</h4>
              </div>
            </div>

          </div>
        </div>
      
        <a href="#!" class="button button--huge button--arrow">SAIBA MAIS</a>
      </section>
      
      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>SERVIÇOS</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
              dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor
              at tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>        
        </header>

        <div class="section__content section__content--top">
          <div class="media media--horizontal media--full">
          
            <a href="financiamento.html" class="media__item">
              <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
              <div class="media__desc media__desc--gray">
                <h4 class="media__title">FINANCIAMENTO</h4>
              </div>
            </a>
          
            <a href="consorcio.html" class="media__item">
              <div class="media__img" style="background-image: url(assets/img/p2.jpg);"></div>
              <div class="media__desc media__desc--red">
                <h4 class="media__title">CONSÓRCIO</h4>
              </div>
            </a>
          
            <a href="consignado.html" class="media__item">
              <div class="media__img" style="background-image: url(assets/img/p3.jpg);"></div>
              <div class="media__desc media__desc--blue">
                <h4 class="media__title">VENDA SEU CARRO</h4>
              </div>
            </a>
          
          </div>
        </div>
      </section>

      <section class="section newsletter">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>ASSINE NOSSO NEWSLETTER</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
              dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>        
          </div>
        </header>

        <div class="k-container">
          <div class="section__content">
            <form class="form form--inline" id="formNewsletter">
              <div class="form__control">
                <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                <span class="form__error">*</span>
              </div>
        
              <div class="form__control">
                <input type="email" class="input" placeholder="E-MAIL" name="email">
                <span class="form__error">*</span>
              </div>
        
              <div class="form__control">
                <button type="submit" class="button button--arrow button--large">cadastrar</button>
              </div>
            </form>

            <small class="newsletter__small">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem
              ipsum dolor sit amet, consectetur adipiscing elit.
            </small>
          </div>
        </div>
      </section>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>KIKOAUTOS NO INSTAGRAM</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
              dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>
      
        <div class="section__content">
          <div id="instafeed" class="instafeed"></div>
        </div>

        <a hreft="https://www.instagram.com/kikoautos" class="instafeed__link" target="_blank">
           https://www.instagram.com/kikoautos
        </a>
      </section>
