<section class="banner js-banner-slider">
	<?php for($i=0;$i<count($bannerPrincipal);$i++){  ?>  
		<a href="<?=$bannerPrincipal->link?>">
		<div class="banner__item" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$bannerPrincipal[$i]->idAlbum?>/<?=$bannerPrincipal[$i]->file?>);"></div>
		</a>
	<?php } ?>
</section>

<section class="section">

	<header class="section__header">
	  <div class="container">
	    <div class="col-md-8 col-md-offset-2">
	      <h2>Novos</h2>
	      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
	        dolor vitae accumsan. interdum hendrerit lacinia.</p>
	    </div>
	  </div>
	</header>

	<div class="section__content">
	
	  <div class="grid-slider js-grid-slider">
	
	    <?php
	
		//Seleciona veciculos destacados
		for($x=0;$x<count($veiculoDestaqueNovos);$x++){ 
			
			$rowDestaqueNovo = $veiculoDestaqueNovos[$x]; 	
			
			$marcaNovo 			= DAOFactory::getMarcaDAO()->load($rowDestaqueNovo->idMarca);
			$transmissaoNovo 	= DAOFactory::getTransmissaoDAO()->load($rowDestaqueNovo->idTransmissao);
			$categoriaNovo	 	= DAOFactory::getVeiculoCategoriaDAO()->load($rowDestaqueNovo->idVeiculoCategoria);
			$capaNovo 			= DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowDestaqueNovo->idAlbum.'" ORDER BY ordem ASC LIMIT 1 '); 
		
		?>
	
	    <a href="/veiculo/<?=$rowDestaqueNovo->alias?>/<?=$rowDestaqueNovo->idVeiculo?>" class="grid__item">
	      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowDestaqueNovo->idAlbum?>/<?=$capaNovo[0]->file?>);"></div>
	      <div class="grid__desc">
	        <h3 class="grid__title"><?=$marcaNovo->nome?> <?=$rowDestaqueNovo->modelo?> <?=$rowDestaqueNovo->anoFabricacao?>/<?=$rowDestaqueNovo->anoModelo?></h3>
	        <p class="grid__text"><?=$rowDestaqueNovo->conservacao?> / <?=$transmissaoNovo->tipo?> / <?=$categoriaNovo->nome?></p>
	        <div class="grid__price">
	          R$ <?=$rowDestaqueNovo->preco?>
	        </div>
	      </div>
	    </a>
	    
	    <a href="/veiculo/<?=$rowDestaqueNovo->alias?>/<?=$rowDestaqueNovo->idVeiculo?>" class="grid__item">
	      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowDestaqueNovo->idAlbum?>/<?=$capaNovo[0]->file?>);"></div>
	      <div class="grid__desc">
	        <h3 class="grid__title"><?=$marcaNovo->nome?> <?=$rowDestaqueNovo->modelo?> <?=$rowDestaqueNovo->anoFabricacao?>/<?=$rowDestaqueNovo->anoModelo?></h3>
	        <p class="grid__text"><?=$rowDestaqueNovo->conservacao?> / <?=$transmissaoNovo->tipo?> / <?=$categoriaNovo->nome?></p>
	        <div class="grid__price">
	          R$ <?=$rowDestaqueNovo->preco?>
	        </div>
	      </div>
	    </a>
	    
	    <a href="/veiculo/<?=$rowDestaqueNovo->alias?>/<?=$rowDestaqueNovo->idVeiculo?>" class="grid__item">
	      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowDestaqueNovo->idAlbum?>/<?=$capaNovo[0]->file?>);"></div>
	      <div class="grid__desc">
	        <h3 class="grid__title"><?=$marcaNovo->nome?> <?=$rowDestaqueNovo->modelo?> <?=$rowDestaqueNovo->anoFabricacao?>/<?=$rowDestaqueNovo->anoModelo?></h3>
	        <p class="grid__text"><?=$rowDestaqueNovo->conservacao?> / <?=$transmissaoNovo->tipo?> / <?=$categoriaNovo->nome?></p>
	        <div class="grid__price">
	          R$ <?=$rowDestaqueNovo->preco?>
	        </div>
	      </div>
	    </a>
	    
	    <a href="/veiculo/<?=$rowDestaqueNovo->alias?>/<?=$rowDestaqueNovo->idVeiculo?>" class="grid__item">
	      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowDestaqueNovo->idAlbum?>/<?=$capaNovo[0]->file?>);"></div>
	      <div class="grid__desc">
	        <h3 class="grid__title"><?=$marcaNovo->nome?> <?=$rowDestaqueNovo->modelo?> <?=$rowDestaqueNovo->anoFabricacao?>/<?=$rowDestaqueNovo->anoModelo?></h3>
	        <p class="grid__text"><?=$rowDestaqueNovo->conservacao?> / <?=$transmissaoNovo->tipo?> / <?=$categoriaNovo->nome?></p>
	        <div class="grid__price">
	          R$ <?=$rowDestaqueNovo->preco?>
	        </div>
	      </div>
	    </a>
	    
	    <?php } ?>
	  
	  </div>
	</div>

	<a href="/estoque" class="button button--huge button--arrow">VER TODOS</a> 

</section>


<section class="grid section section--white">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>SEMINOVOS</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
        ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
    </div>
  </div>
</header>
<div class="section__content">

  <div class="grid js-grid-semi">      
    
    <?php
	//Seleciona veciculos destacados
	for($sm=0;$sm<count($veiculoDestaqueSM);$sm++){ 
		
		$rowDestaque = $veiculoDestaqueSM[$sm]; 	
		
		$marca 			= DAOFactory::getMarcaDAO()->load($rowDestaque->idMarca);
		$transmissao 	= DAOFactory::getTransmissaoDAO()->load($rowDestaque->idTransmissao);
		$categoria	 	= DAOFactory::getVeiculoCategoriaDAO()->load($rowDestaque->idVeiculoCategoria);
		$capa 			= DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowDestaque->idAlbum.'" ORDER BY ordem ASC LIMIT 1 '); 
	
	?>
	
    <a href="/veiculo/<?=$rowDestaque->alias?>/<?=$rowDestaque->idVeiculo?>" class="grid__item">
      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowDestaque->idAlbum?>/<?=$capa[0]->file?>);"></div>
      <div class="grid__desc">
        <h3 class="grid__title"><?=$marca->nome?> <?=$rowDestaque->modelo?> <?=$rowDestaque->anoFabricacao?>/<?=$rowDestaque->anoModelo?>></h3>
        <p class="grid__text"><?=$rowDestaque->conservacao?> / <?=$transmissao->tipo?> / <?=$categoria->nome?></p>
        <div class="grid__price">
          R$ <?=$rowDestaque->preco?>
        </div>
      </div>
    </a>
    
    <?php } ?>
    
  </div>
</div>

<a href="/estoque" class="button button--huge button--arrow">VER TODOS</a>
</section>

<section class="section">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>NOSSOS DIFERENCIAIS</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
      dolor vitae accumsan. interdum hendrerit lacinia.</p>
    </div>
  </div>
</header>
<div class="section__content">
  <div class="media media--col4 media--center">

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre"><img src="assets/img/variedade.png" alt="Variedade de marcas"></a>
      </div>
       <div class="media__desc">
         <h4 class="media__title">Variedade de<br>marcas</h4>
       </div>
    </div>

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre"><img src="assets/img/negociacao.png" alt="Negociação facilitada"></a>
      </div>
      <div class="media__desc">
        <h4 class="media__title">Negociação<br>facilitada</h4>
      </div>
    </div>

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre"><img src="assets/img/certificacao.png" alt="Certificação de blindados"></a>
      </div>
      <div class="media__desc">
        <h4 class="media__title">Certificação de<br>blindados</h4>
      </div>
    </div>

    <div class="media__item">
      <div class="media__img">
        <a href="/sobre"><img src="assets/img/estrutura.png" alt="Estrutura Moderna"></a>
      </div>
      <div class="media__desc">
        <h4 class="media__title">Estrutura<br>Moderna</h4>
      </div>
    </div>

  </div>
</div>

<a href="/sobre" class="button button--huge button--arrow">SAIBA MAIS</a>
</section>

<section class="section section--white">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>SERVIÇOS</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
      dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor
      at tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
    </div>
  </div>        
</header>

<div class="section__content section__content--top">
  <div class="media media--horizontal media--full">
  
    <a href="/financiamento" class="media__item">
      <div class="media__img" style="background-image: url(assets/img/p1.jpg);"></div>
      <div class="media__desc media__desc--gray">
        <h4 class="media__title">FINANCIAMENTO</h4>
      </div>
    </a>
  
    <a href="/consorcio" class="media__item">
      <div class="media__img" style="background-image: url(assets/img/p2.jpg);"></div>
      <div class="media__desc media__desc--red">
        <h4 class="media__title">CONSÓRCIO</h4>
      </div>
    </a>
  
    <a href="/consignado" class="media__item">
      <div class="media__img" style="background-image: url(assets/img/p3.jpg);"></div>
      <div class="media__desc media__desc--blue">
        <h4 class="media__title">VENDA SEU CARRO</h4>
      </div>
    </a>
  
  </div>
</div>
</section>

<section class="section newsletter">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>ASSINE NOSSO NEWSLETTER</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
      dolor vitae accumsan. interdum hendrerit lacinia.</p>
    </div>        
  </div>
</header>

<div class="k-container">
  <div class="section__content">
    <form class="form form--inline" id="formNewsletter">
      <div class="form__control">
        <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
        <span class="form__error">*</span>
      </div>

      <div class="form__control">
        <input type="email" class="input" placeholder="E-MAIL" name="email">
        <span class="form__error">*</span>
      </div>

      <div class="form__control">
        <button type="submit" class="button button--arrow button--large">cadastrar</button>
      </div>
    </form>

    <small class="newsletter__small">
       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem
      ipsum dolor sit amet, consectetur adipiscing elit.
    </small>
  </div>
</div>
</section>

<section class="section section--white">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>KIKOAUTOS NO INSTAGRAM</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
      dolor vitae accumsan. interdum hendrerit lacinia.</p>
    </div>
  </div>
</header>

<div class="section__content">
  <div id="instafeed" class="instafeed"></div>
</div>

<a hreft="https://www.instagram.com/kikoautos" class="instafeed__link" target="_blank">
   https://www.instagram.com/kikoautos
</a>
</section>
