<section class="section">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>SOBRE A KIKOAUTOS</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
              dolor vitae accumsan.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <div class="sobre">
              <div class="sobre__column">
                <p>
                   A KikoAutos tem como foco oferecer a seus clientes serviços agregados, não apenas um excelente automóvel 0KM ou seminovo.
                  Por isso, serve como vitrine para o mercado e se destaca pelo seu atendimento de qualidade, consultores a ltamente treinados
                  e infraestrutura moderna e diferenciada.
                  <br>Desde 1988 é pioneira em Taubaté e região, investindo em tecnologia e na força do
                  mercado digital como tendência e futuro para o comércio automotivo.
                </p> 

                <h3 class="section__h3">Missão e Valores</h3>

                <p>
                   Comercializar veículos automotores novos e seminovos através da excelência em atendimento, profissionalismo e foco no cliente em um ambiente inovador e dinâmico.
                </p>

                <h3 class="section__h3">Visão</h3>
                
                <p>Ser a melhor opção multimarcas para toda linha 0km e seminovos.</p>
              </div>
              <div class="sobre__column">
                <div class="sobre-slider js-slider-sobre">
                  <div class="sobre-slider__item" style="background-image:url(assets/img/sobre.jpg)"></div>
                  <div class="sobre-slider__item" style="background-image:url(assets/img/sobre.jpg)"></div>
                  <div class="sobre-slider__item" style="background-image:url(assets/img/sobre.jpg)"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="section section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>HISTÓRIA</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
              dolor vitae accumsan.</p>
            </div>
          </div>
        </header>
        <div class="section__content">
          <div class="container">
            <div class="historia-slider js-slider-historia">
              <div class="historia-slider__item">
                <h4>1990</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                  ac dolor vitae accumsan.</p>
              </div>

              <div class="historia-slider__item">
                <h4>1994</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                  ac dolor vitae accumsan.</p>
              </div>
              <div class="historia-slider__item">
                <h4>2000</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                dolor vitae accumsan. interdum hendrerit lacinia.</p>
              </div>

              <div class="historia-slider__item">
                <h4>2006</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis.</p>
              </div>

              <div class="historia-slider__item">
                <h4>Atualmente</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                dolor vitae accumsan.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="section--white">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>NOSSOS DIFERENCIAIS</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper
                ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>

        <div class="section__content">
          <div class="container">
            <div class="row">
              <div class="col-sm-4">
                <div class="diferencial__item">
                  <img src="assets/img/variedade.png" alt="Variedade">
                  <h4>
                     Variedade<br>de marcas
                  </h4>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="diferencial__item">
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                    dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor
                    at tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.
                  </p>
                </div>
                
              </div>
            </div>

            <div class="row">
              <div class="col-sm-4">
                <div class="diferencial__item">
                  <img src="assets/img/negociacao.png" alt="Variedade">
                  <h4>
                     Negociação<br>facilitada
                  </h4>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="diferencial__item">
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                    dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor
                    at tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.
                  </p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-4">
                <div class="diferencial__item">
                  <img src="assets/img/certificacao.png" alt="Variedade">
                  <h4>
                     Certificação<br>de blindados
                  </h4>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="diferencial__item">
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                    dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor
                    at tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.
                  </p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-4">
                <div class="diferencial__item">
                  <img src="assets/img/estrutura.png" alt="Variedade">
                  <h4>
                     Estrutura<br>Moderna
                  </h4>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="diferencial__item">
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut nunc. Semper ac
                    dolor vitae accumsan. interdum hendrerit lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor
                    at tellus feugiat congue quis ut nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.
                  </p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      <section class="section newsletter">
        <header class="section__header">
          <div class="container">
            <div class="col-md-8 col-md-offset-2">
              <h2>ASSINE NOSSO NEWSLETTER</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ac tortor at tellus feugiat congue quis ut
                nunc. Semper ac dolor vitae accumsan. interdum hendrerit lacinia.</p>
            </div>
          </div>
        </header>

        <div class="k-container">
          <div class="section__content">
            <form class="form form--inline" id="formNewsletter">
              <div class="form__control">
                <input type="text" class="input" placeholder="NOME COMPLETO" name="nome">
                <span class="form__error">*</span>
              </div>

              <div class="form__control">
                <input type="email" class="input" placeholder="E-MAIL" name="email">
                <span class="form__error">*</span>
              </div>

              <div class="form__control">
                <button type="submit" class="button button--arrow button--large">cadastrar</button>
              </div>
            </form>

            <small class="newsletter__small">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum
              dolor sit amet, consectetur adipiscing elit.
            </small>
          </div>
        </div>
      </section>