<section>
<div class="container">
  
  <div class="row">
  <ol class="breadcrumb">
    <li>
      <a href="/estoque">ESTOQUE</a>
    </li>
<!--
    <li>
      <a href="/estoque?<?=$veiculo[0]->conservacao?>"><?=strtoupper($veiculo[0]->conservacao)?></a>
    </li>
-->
    <li class="active"><?=strtoupper($marca->nome)?> <?=strtoupper($veiculo[0]->modelo)?></li>
  </ol>
  </div>

  <div class="row">
    <div class="section__header section--text-left">
      <div class="col-sm-2">
        <?php if($marca->logo!=''){ ?> <img src="<?=$URLSITE?>/assets/img/marcas/<?=$marca->logo?>" alt="<?=$marca->nome?>"><?php } ?>
      </div>
      <div class="col-sm-10">
        <h2>
           <?=$marca->nome?> <?=$veiculo[0]->modelo?>
        </h2>

        <p>
	    <?php
	    
	    if($veiculo[0]->observacoes==''){
		    
		    echo 'Seu carro novo esta esperando por você! Não perca esta oportunidade: '.$marca->nome.' '.$veiculo[0]->modelo.', modelo '.$veiculo[0]->anoFabricacao.'/'
		    .$veiculo[0]->anoModelo.', cor '.$cor->nome.', com '.$veiculo[0]->km.'km por apenas R$ '.$veiculo[0]->preco.' aceitamos seu usado na troca.';
		    
		    
	    }else{
		    
		    echo($veiculo[0]->observacoes);
	    }    
	        
	        
        ?></p>
        
      </div>
    </div>
  </div>
  <div class="row">
    <div class="section__content">
      <div class="col-md-8">
        <div class="veiculo-slider js-slider-veiculo">
	      
	      <?php 
		      
		      for($i=0;$i<count($album);$i++){  
		      if($album[$i]->nome=='') $textAlt = ''.$marca->nome.' '.$veiculo[0]->modelo; else $textAlt = $album[$i]->nome;
		      
	      ?>  
          	<div title="<?=$textAlt?>" class="veiculo-slider__item" data-fancybox="gallery" href="<?=$URLSITE?>/assets/img/albuns/album_<?=$album[$i]->idAlbum?>/<?=$album[$i]->file?>" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$album[$i]->idAlbum?>/<?=$album[$i]->file?>);"></div>
		  <?php } ?>
          
        </div>

        <div class="veiculo-slider-nav js-slider-veiculo-nav">
	      <?php 
		      
		      for($i=0;$i<count($album);$i++){  
			      
			      if($album[$i]->nome=='') $textAlt = ''.$marca->nome.' '.$veiculo[0]->modelo; else $textAlt = $album[$i]->nome;
		      ?>  
          <div title="<?=$textAlt?>" class="veiculo-slider-nav__item" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$album[$i]->idAlbum?>/<?=$album[$i]->file?>);"></div>
          
          <?php } ?>
        </div>
      </div>
      <div class="col-md-4">
        <div class="veiculo-info">
          <ul class="veiculo-list">
            <li><span>MARCA</span> <?=$marca->nome?></li>
            <li><span>MODELO</span> <?=$veiculo[0]->modelo?></li>
            <li><span>COR</span> <?=$cor->nome?></li>
            <li><span>ANO/MODELO</span> <?=$veiculo[0]->anoFabricacao?>/<?=$veiculo[0]->anoModelo?></li>
            <li><span>PREÇO</span> R$ <?=$veiculo[0]->preco?></li>
          </ul>

          <div class="veiculo-desc">
            <small>
               OUTRAS INFORMAÇÕES:
            </small>
            <ul>
              
				<?php if($veiculo[0]->km!=''){ ?><li>Km: <span><?=$veiculo[0]->km?></span></li><?php } ?>  
				<?php if($veiculo[0]->motor!=''){ ?><li>Motor: <span><?=$veiculo[0]->motor?></span></li><?php } ?>
				<?php if($veiculo[0]->potencia!=''){ ?><li>Potência: <span><?=$veiculo[0]->potencia?></span></li><?php } ?>
				<?php if($veiculo[0]->aceleracao!=''){ ?><li>Aceleração: <span><?=$veiculo[0]->aceleracao?></span></li><?php } ?>
				<?php if($veiculo[0]->airbag!=''){ ?><li>Airbag: <span><?=$veiculo[0]->airbag?></span></li><?php } ?>
				<?php if($veiculo[0]->garantiaFabrica!=''){ ?><li>Garantia de fábrica: <span><?=$veiculo[0]->garantiaFabrica?></span></li><?php } ?>
				<?php if($combustivel->tipo!=''){ ?><li>Combustível: <span><?=$combustivel->tipo?></span></li><?php } ?>
				<?php if($transmissao->tipo!=''){ ?><li>Transmissão: <span><?=$transmissao->tipo?></span></li><?php } ?>
				<?php if($veiculo[0]->placa!=''){ ?><li>Placa: <span>XXX-<?=substr($veiculo[0]->placa, -4)?></span></li><?php } ?>
				<?php if($veiculo[0]->Portas!=''){ ?><li>Portas: <span><?=$veiculo[0]->portas?></span></li><?php } ?>
				<?php if($veiculo[0]->Motor!=''){ ?><li>Motor: <span><?=$veiculo[0]->motor?></span></li><?php } ?>
				<?php if($veiculo[0]->multimidia!=''){ ?><li>Multimídia: <span><?=$veiculo[0]->multimidia?></span></li><?php } ?>
				<?php if($veiculo[0]->bancos!=''){ ?><li>Bancos: <span><?=$veiculo[0]->bancos?></span></li><?php } ?>
				<?php if($veiculo[0]->freios!=''){ ?><li>Freios: <span><?=$veiculo[0]->freios?></span></li><?php } ?>
				<?php if($veiculo[0]->farois!=''){ ?><li>Faróis: <span><?=$veiculo[0]->farois?></span></li><?php } ?>
				<?php if($veiculo[0]->rodas!=''){ ?><li>Rodas: <span><?=$veiculo[0]->rodas?></span></li><?php } ?>
				<?php if($sensor->tipo!=''){ ?><li>Sensor de estacionamento: <span><?=$sensor->tipo?></span></li><?php } ?>
				
				<?php if($veiculo[0]->bluetooth=='sim'){ ?><li>Bluetooth: <span><?=strtoupper($veiculo[0]->bluetooth)?></span></li><?php } ?>
				<?php if($veiculo[0]->tetoSolar=='sim' or $veiculo[0]->tetoSolar=='semipanoramico'){ ?><li>Teto Solar: <span><?=strtoupper($veiculo[0]->tetoSolar)?></span></li><?php } ?>
				<?php if($veiculo[0]->conversivel=='sim'){ ?><li>Conversível: <span><?=strtoupper($veiculo[0]->conversivel)?></span></li><?php } ?>
				<?php if($veiculo[0]->pilotoAutomatico=='sim'){ ?><li>Piloto Automático: <span><?=strtoupper($veiculo[0]->pilotoAutomatico)?></span></li><?php } ?>
				<?php if($veiculo[0]->sensorChuva=='sim'){ ?><li>Sensor de Chuva: <span><?=strtoupper($veiculo[0]->sensorChuva)?></span></li><?php } ?>
				<?php if($veiculo[0]->blindado=='sim'){ ?><li>Blindado: <span><?=strtoupper($veiculo[0]->blindado)?></span></li><?php } ?>
			    <?php if($veiculo[0]->observacoes!=''){ ?><li>Observações: <span><?=($veiculo[0]->observacoes)?></span></li><?php } ?>
			    <?php if($veiculo[0]->oferta!=''){ ?><li>Condições especiais: <span><?=($veiculo[0]->oferta)?></span></li><?php } ?>
              
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


</section>

<section class="section">
<header class="section__header">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h2>FAÇA SUA PROPOSTA</h2>
      <p>Deixe seus dados, selecione sua forma de pagamento ideal e deixe sua proposta detalhando o máximo possível sobre sua ideia de negócio.</p>
    </div>
  </div>
</header>
<div class="section__content">
  <div class="container">
    <form class="form" action="" id="formProposta">
      <div class="row">
        <div class="col-md-4">
	        
	      <input type="hidden" class="input" name="idVeiculo" value="<?=$veiculo[0]->idVeiculo?>">
	      <input type="hidden" class="input" name="nomeVeiculo" value="<?=$marca->nome?> <?=$veiculo[0]->modelo?> - <?=$veiculo[0]->anoFabricacao?>/<?=$veiculo[0]->anoModelo?> - R$ <?=$veiculo[0]->preco?>">

          <div class="form__control">
            <input type="text" class="input" placeholder="NOME" name="nome">
          </div>

          <div class="form__control">
            <input type="email" class="input" placeholder="EMAIL" name="email">
          </div>

          <div class="form__control">
            <input type="tel" class="input js-phone" placeholder="TELEFONE" name="telefone">
          </div>
        </div>

        <div class="col-md-8">

          <div class="form__control form__control--select">
            <select class="input" name="formas_pagamento" id="formas_pagamento">
              <option value="0" disabled selected>FORMAS DE PAGAMENTO</option>
              <option value="Pagamento à vista">Pagamento à vista</option>
              <option value="Financiamento">Financiamento</option>
              <option value="Consórcio">Consórcio</option>
              <option value="Meu veículo no negócio">Meu veículo no negócio</option>
              <option value="Outro">Outro</option>
            </select>
          </div>

          <div class="form__control">
            <textarea name="mensagem" class="textarea" placeholder="Olá, estou interessado no veículo Hyundai New Tucson"></textarea>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="form__control">
            <input type="checkbox" name="newsletter" value="1" id="novidades_email" />
            <label for="novidades_email">Receber novidades por e-mail</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form__control text-right">
            <button type="submit" class="button button--arrow button--ghost button--medium">ENVIAR</button>
          </div>
        </div>
      </div>
    </form>
  </div>
  
  <br>
  <div class="container text-center"><a href="/financiamento" class="button button--ghost button--blue button--small">OU SOLICITAR UM FINANCIAMENTO?</a></div>

  
</div>
</section>

<section class="grid section section--white">
<header class="section__header">
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <h2>Veja outros modelos similares</h2>
    </div>
  </div>
</header>
<div class="section__content section__content--top">

  <div class="grid">

	
	<?php
	//Seleciona veciculos destacados
	for($re=0;$re<count($veiculosRelacionados);$re++){ 
		
		$rowRelacionado = $veiculosRelacionados[$re]; 	
		
		$marca 			= DAOFactory::getMarcaDAO()->load($rowRelacionado->idMarca);
		$transmissao 	= DAOFactory::getTransmissaoDAO()->load($rowRelacionado->idTransmissao);
		$categoria	 	= DAOFactory::getVeiculoCategoriaDAO()->load($rowRelacionado->idVeiculoCategoria);
		$capa 			= DAOFactory::getAlbumMidiaDAO()->queryCondList(' idAlbum="'.$rowRelacionado->idAlbum.'" ORDER BY ordem ASC LIMIT 1 '); 
	
	?>
	
    <a href="/veiculo/<?=$rowRelacionado->alias?>/<?=$rowRelacionado->idVeiculo?>" class="grid__item">
      <div class="grid__img" style="background-image: url(<?=$URLSITE?>/assets/img/albuns/album_<?=$rowRelacionado->idAlbum?>/<?=$capa[0]->file?>);"></div>
      <div class="grid__desc">
        <h3 class="grid__title"><?=$marca->nome?> <?=$rowRelacionado->modelo?> <?=$rowRelacionado->anoFabricacao?>/<?=$rowRelacionado->anoModelo?></h3>
        <p class="grid__text"><?=$rowRelacionado->conservacao?> / <?=$transmissao->tipo?> / <?=$categoria->nome?></p>
        <div class="grid__price">
          R$ <?=$rowRelacionado->preco?>
        </div>
      </div>
    </a>
    
    <?php } ?>

    
  </div>
</div>


</section>




<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-servicos.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-newsletter.phtml');	

?>

<?php

	/*
	* Incluse Newsletter
	*	
	*/
	
	include_once('include/section-instagram.phtml');	

?>